export const GET_ALL_BARANGAYS = 'GET_ALL_BARANGAYS';
export const GET_BARANGAY = 'GET_BARANGAY';
export const BARANGAY_MESSAGE = 'BARANGAY_MESSAGE';
export const BARANGAYS_RESET = 'BARANGAYS_RESET';
export const BARANGAYS_ERROR = 'BARANGAYS_ERROR';
export const BARANGAYS_LOADING = 'BARANGAYS_LOADING';
