export const GET_ALL_EMERGENCIES = 'GET_ALL_EMERGENCIES';
export const EMERGENCIES_LOADING = 'EMERGENCIES_LOADING';
export const EMERGENCIES_ERROR = 'EMERGENCIES_ERROR';
export const EMERGENCIES_SUCCESS = 'EMERGENCIES_SUCCESS';
export const EMERGENCIES_MESSAGE = 'EMERGENCIES_MESSAGE';
