export const GET_ALL_EMERGENCY_TYPES = 'GET_ALL_EMERGENCY_TYPES';
export const GET_EMERGENCY_TYPE = 'GET_EMERGENCY_TYPE';
export const EMERGENCY_TYPE_MESSAGE = 'EMERGENCY_TYPE_MESSAGE';
export const EMERGENCY_TYPES_RESET = 'EMERGENCY_TYPES_RESET';
export const EMERGENCY_TYPES_ERROR = 'EMERGENCY_TYPES_ERROR';
export const EMERGENCY_TYPES_LOADING = 'EMERGENCY_TYPES_LOADING';
