export const GET_ALL_USER_TYPES = 'GET_ALL_USER_TYPES';
export const GET_USER_TYPE = 'GET_USER_TYPE';
export const USER_TYPE_MESSAGE = 'USER_TYPE_MESSAGE';
export const USER_TYPES_RESET = 'USER_TYPES_RESET';
export const USER_TYPES_ERROR = 'USER_TYPES_ERROR';
export const USER_TYPES_LOADING = 'USER_TYPES_LOADING';
